import { Router, Request, Response } from 'express';
import { v4 as uuidv4 } from 'uuid';
import { logger } from '../utils/logger';

export const projectsRouter = Router();

// In-memory store (fallback when DB is unavailable)
const projectStore = new Map<string, any>();

// List all projects
projectsRouter.get('/', async (_req: Request, res: Response) => {
  try {
    const projects = Array.from(projectStore.values())
      .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
    res.json({ projects, total: projects.length });
  } catch (error) {
    logger.error('Failed to list projects:', error);
    res.status(500).json({ error: 'Failed to list projects' });
  }
});

// Create project
projectsRouter.post('/', async (req: Request, res: Response) => {
  try {
    const { name, description, type = 'app', config = {} } = req.body;
    if (!name) return res.status(400).json({ error: 'Project name is required' });

    const project = {
      id: uuidv4(),
      name,
      description: description || '',
      type,
      config,
      files: {},
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    projectStore.set(project.id, project);
    logger.info(`Project created: ${project.name} (${project.id})`);
    res.status(201).json(project);
  } catch (error) {
    logger.error('Failed to create project:', error);
    res.status(500).json({ error: 'Failed to create project' });
  }
});

// Get project by ID
projectsRouter.get('/:id', async (req: Request, res: Response) => {
  try {
    const project = projectStore.get(req.params.id);
    if (!project) return res.status(404).json({ error: 'Project not found' });
    res.json(project);
  } catch (error) {
    res.status(500).json({ error: 'Failed to get project' });
  }
});

// Update project
projectsRouter.put('/:id', async (req: Request, res: Response) => {
  try {
    const project = projectStore.get(req.params.id);
    if (!project) return res.status(404).json({ error: 'Project not found' });

    const updated = {
      ...project,
      ...req.body,
      id: project.id,
      createdAt: project.createdAt,
      updatedAt: new Date().toISOString()
    };

    projectStore.set(project.id, updated);
    res.json(updated);
  } catch (error) {
    res.status(500).json({ error: 'Failed to update project' });
  }
});

// Delete project
projectsRouter.delete('/:id', async (req: Request, res: Response) => {
  try {
    if (!projectStore.has(req.params.id)) {
      return res.status(404).json({ error: 'Project not found' });
    }
    projectStore.delete(req.params.id);
    res.json({ deleted: true });
  } catch (error) {
    res.status(500).json({ error: 'Failed to delete project' });
  }
});

// Generate code for project (AI-powered)
projectsRouter.post('/:id/generate', async (req: Request, res: Response) => {
  try {
    const project = projectStore.get(req.params.id);
    if (!project) return res.status(404).json({ error: 'Project not found' });

    const { prompt, target = 'component' } = req.body;
    
    // Mock generation (will be replaced with real AI)
    const generated = {
      target,
      prompt,
      code: `// Generated by Engine Alto AI\n// Prompt: ${prompt}\n\nexport function GeneratedComponent() {\n  return <div>Generated: ${prompt}</div>;\n}\n`,
      language: 'typescript',
      timestamp: new Date().toISOString()
    };

    res.json(generated);
  } catch (error) {
    res.status(500).json({ error: 'Failed to generate code' });
  }
});
